### ISSUE TITLE
No builds available from Fedora Copr

### ISSUE THREAD

**Issue by Bob131** [valum-framework/valum#122]
I noticed that https://copr.fedoraproject.org/coprs/arteymix/valum-framework/ doesn't have any submitted builds. Any particular reason why?

If its due to a lack of time/interest, I'd be happy to assist in this regard

**Comment by arteymix** [comment]
I tried once, it failed and I did not have a relevant log of what happened so I left this aside.

The best way you could assist would be by investigating the Copr build. You can generate a source RPM by running:

```
waf dist
mv valum-0.2.0.tar.bz2 ~/rpmbuild/SOURCES/
rpmbuild -bs build/valum.spec
```

I'll try to rebuild it on my side, just to make sure.

**Comment by Bob131** [comment]
ah, easy fix. Your BuildRequires in the spec is not thorough enough. I can submit a patch once I get it going if you like

**Comment by arteymix** [comment]
As it will get more formal, it could be a good thing to add a paragraph about generating the RPM package in the user documentation.

Thanks for the work ;)
