### ISSUE TITLE
Incorrect path to valum.h in output VAPI

### ISSUE THREAD

**Issue by Bob131** [valum-framework/valum#125]
The header path in `CCode` annotations is "valum.h" whereas the header is in fact installed to "valum/valum.h" by waf and subsequently in the RPM package. I'm kind of hoping this is an easy fix for you since compilation and build tools are still a dark magic to me (embarrassing, right?). If not, I can start digging in the morn.

Also, I've noticed a few formatting and other hiccups in the docs. Would it be appropriate for me to lump all the fixes into one big commit? I figure tackling the low-hanging fruit rather than getting elbows-deep in stuff I mightn't the knowledge to undertake would be a better place to start

**Comment by arteymix** [comment]
Inclusion flags are resolved with `pkg-config` by `valac`, so it's not dark magic ;) More details here: http://www.freedesktop.org/wiki/Software/pkg-config/

You can run the following command to see it in action:

```bash
pkg-config --cflags --libs valum
```

Once installed, you can compile and run your project as follow:

```bash
vala --pkg=valum --vapidir=some/vapi/dir/containing/ctpl/and/fcgi app.vala
```

It might be a good thing to install `ctpl.vapi` and `fcgi.vapi` though..

**Comment by arteymix** [comment]
@Bob131 If you want to dig the documentation and fix typos, be my guest!

**Comment by Bob131** [comment]
...I forgot to add valum to my configure.ac. Don't mind me :P
