### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by Matrix-Zhang** [valum-framework/valum#136]
1)build docs fail:

Running Sphinx v1.2.3
loading pickled environment... not yet created

Theme error:
no theme named 'sphinx_rtd_theme' found (missing theme.conf?)

Waf: Leaving directory `/opt/projects/valum/build'
Build failed
-> task in 'app' failed (exit status 1):
{task 140638660706192: valac app.vala -> app.c}
''
-> task in 'app' failed (exit status 1):
{task 140638660769040: valac app.vala -> app.c}
''
-> task in '' failed (exit status 1):
{task 140638660703632: ${SPHINXBUILD} -b html ../docs docs gnu-lgpl-v3.0.rst,application.rst,ctpl.rst,getting-started.rst,hacking.rst,index.rst,installation.rst,module.rst,configuration.rst,index.rst,json.rst,persistence.rst,scripting.rst,static-resource.rst,redirection-and-error.rst,route.rst,router.rst,connection.rst,converters.rst,cookies.rst,filters.rst,index.rst,request.rst,response.rst,cgi.rst,fastcgi.rst,index.rst,scgi.rst,soup.rst -> }
' /usr/bin/sphinx-build -b html ../docs docs '

2)build example fail:

In file included from examples/markdown/app.c:7:0:
/opt/projects/valum/build/static/valum.h:15:17: fatal error: gee.h: no such file or directory

**Comment by arteymix** [comment]
You are missing the `sphinx_rtd_theme` Python package.

You can also comment out the `html_theme` option in `conf.py`, it will use the default theme.

**Comment by arteymix** [comment]
Try to install gee development package, I don't think that you have the headers installed.

**Comment by Matrix-Zhang** [comment]
i have installed the libgee-0.8.....

**Comment by arteymix** [comment]
I assume so since you have apparently passed the `configure` step.

What GNU/Linux distribution are you using? libgee comes in two flavours (0.8 and 0.10 I think), so it might cause issue with the headers location.

**Comment by Matrix-Zhang** [comment]
i'm using ubuntu 15.10

i just installed the package libgee-0.8-dev...

**Comment by arteymix** [comment]
What does `pkg-config gee-0.8 --cflags --libs` returns?

Is `gee.h` in `/usr/include/gee-0.8` ?

**Comment by Matrix-Zhang** [comment]
pkg-config gee-0.8 --cflags --libs

-I/usr/include/gee-0.8 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -lgee-0.8 -lgobject-2.0 -lglib-2.0

**Comment by arteymix** [comment]
I will attempt to reproduce your build with Docker with your version of Ubuntu.

**Comment by arteymix** [comment]
I could not reproduce your build error. You might need the vala-team PPA:

```
add-apt-repository --yes ppa:vala-team
```

**Comment by Matrix-Zhang** [comment]
i'm also not reproduce the error too....with change to another notebook....
