### ISSUE TITLE
cant't read body in scgi mode 

### ISSUE THREAD

**Issue by Matrix-Zhang** [valum-framework/valum#140]
in scgi mode, read from req.body would block...nothing will be readed....

for example :

curl -d "data=1" http://localhost:3003/test

the data=1 form data can't be readed....

and i change to fastcgi, it would be ok

**Comment by arteymix** [comment]
Flattening `InputStream` is tricky (see #128) and will be addressed in the next release with `flatten` #121 

Until then, the best way to process it is described here: https://github.com/valum-framework/valum/blob/flatten/src/vsgi-request.vala#L157

**Comment by Matrix-Zhang** [comment]
3ks a lot....

**Comment by Matrix-Zhang** [comment]
Hi, I'm merge the flatten to my valum...
but it still blocked...

			try {
				router.post(rule, (req, res) => {
					try {
						var data = req.flatten();
						var form_params = Soup.Form.decode ((string)data);
						callback(req, res, form_params);
					} catch(GLib.IOError error) {
						GLib.warning(error.message);
					}
				});
			} catch(GLib.RegexError error) {
				GLib.warning(error.message);
			}

the data never be returned ...

**Comment by Matrix-Zhang** [comment]
then i tried the async edition,

try {
						req.flatten_async.begin(GLib.Priority.DEFAULT, null, (obj, result) => {
							message("11111");
						});
						//var form_params = Soup.Form.decode ((string)data);
						//callback(req, res, form_params);
					} catch(GLib.IOError error) {
						GLib.warning(error.message);
					}

the "111111" never be showed....

**Comment by arteymix** [comment]
You are effectively right, the input stream blocks while splicing. This is rather strange; I will investigate the problem.

**Comment by arteymix** [comment]
@Matrix-Zhang It works with libsoup-2.4 if you want to test/develop your application

**Comment by Matrix-Zhang** [comment]
okay, i use VSGI.Ssoup to develop first, but you kndow, for more stable and efficiency in production environment. lighttpd + scgi is better than soup...

**Comment by arteymix** [comment]
@Matrix-Zhang You can try the new master tip, I have fixed the issue.
