### ISSUE TITLE
Potential Licensing Fiasco

### ISSUE THREAD

**Issue by Digi59404** [valum-framework/valum#145]
Valum is licensed under LGPL V3. 
CTPL is licensed under GPL V3.

Because of the way GPL is licensed and the inclusion of GPL code into Valum. Any works created with Valum must be licensed under GPL. There is a graph for this on GNU that explains it. http://www.gnu.org/licenses/gpl-faq.html#AllCompatibility

In the future there may be much confusion regarding this or someone may use Valum and violate the GPL unknowingly. To resolve this potential fiasco - You should either license Valum as GPL - Or Replace CTPL with something like Mustache (Of which there were plans).

**Comment by arteymix** [comment]
It is effectively the case. I will remove the CTPL code from Valum and distribute it separately under GPLv3.

The plan was to _not_ ship a templating engine, but provide an implementation of Mustache that would be very friendly with GIO stream API. I'm working on this actually and it should be ready in a couple of weeks.

**Comment by Digi59404** [comment]
@arteymix  Thank you - I hate to bring this up, and be the guy that put's in /that/ ticket. But I was looking to possible use Valum and I uncovered this.

Regarding Mustache - Do you need help? I noticed the repo is empty for the most part but i'd be interested in helping.

**Comment by arteymix** [comment]
@Digi59404 it's all right, had to be done anyway.

If you don't mind, of course you can get involved. I will upload a prototype in a few days, but in short:

 - environment is provided by a [Json.Object](http://valadoc.org/#!api=json-glib-1.0/Json.Object) (see json-glib-1.0) with support for lambdas
 - recursive descent streaming parser and renderer (all asynchronous)
 - integration for partials and custom rendering provided by a context 
 - written in Vala, of course

**Comment by b4n** [comment]
FWIW, I (as CTPL author) would probably be happy to re-license under LGPL if the current license prevents you from using the library.  And actually, as CTPL doesn't really create something totally unseen before, it might make even more sense to make it LGPL.

**Comment by Digi59404** [comment]
@b4n Hey man - So, The reason I brought this up is because my company is looking to working and building out a CMS based on Vala. We were looking at Valum and Ambition. We chose Ambition because we as a company can't ship a CMS to a client under GPL. That would mean all their themes, assets, designs, etc all were GPL.

I know this is a common problem in the FOSS community and one reason why many ship code under MIT.

**Comment by arteymix** [comment]
@b4n shipping a templating engine defeats the idea of a micro-framework, I would rather see people integrate it (or any other templating engine) directly in their project

@Digi59404 Valum still need some work to become production-ready (missing critical features like multipart stream #105), so you would have clearly hit a wall at some point of your development

I like the MIT, but in the context of a GLib ecosystem, it's nice to remain around the LGPL license.
