### ISSUE TITLE
application runing failed.....

### ISSUE THREAD

**Issue by Matrix-Zhang** [valum-framework/valum#154]
after the comit 3b94bb8, the vsgi applistion can not starup....

(process:30797): GLib-GObject-CRITICAL **: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

** (process:30797): CRITICAL **: vsgi_server_set_application_callback: assertion 'self != NULL' failed
** Message: fuck run here.

(process:30797): GLib-GIO-CRITICAL **: g_application_run: assertion 'G_IS_APPLICATION (application)' failed

i add some log in the C file...

i checkout that the function vsgi_scgi_server_new, return NULL ?

**Comment by arteymix** [comment]
Is it related to #155 ?

I don't have sufficient information to tell you what's going wrong here. It just seems that the shared library for SCGI is not loaded.

In the meantime, you should use a [release](https://github.com/valum-framework/valum/releases), which are more stable. I fixed an important issue with SCGI that practically doubled the throughput.

**Comment by Matrix-Zhang** [comment]
no, it is new issue in master branch...

i change to the latest release 0.28 is OK

**Comment by arteymix** [comment]
I got the same issue with the installed files on my side. I must have missed something when I extracted implementations into separated shared libraries.

I will backport fixes for FastCGI into another hotfix release. I got the async I/O working :)

I'll fix that, promise!

**Comment by arteymix** [comment]
It's the `[ModuleInit]` directives that breaks everything. It registers GObject types only through `plugin_init`, which is not desirable.

I will figure out something when merging #130.

**Comment by arteymix** [comment]
@Matrix-Zhang I backported the fixes for FastCGI to support async I/O in [v0.2.9](https://github.com/valum-framework/valum/releases/tag/v0.2.9) (I think you wanted to use that at first)

SCGI is much more performant though.
