### ISSUE TITLE
incompatible with newest vala

### ISSUE THREAD

**Issue by Matrix-Zhang** [valum-framework/valum#175]
when use newset vala compile valum, there is an error:

vsgi-chunked-encoder.vala:36.3-36.32: error: overriding method `VSGI.ChunkedEncoder.convert' is incompatible with base method `GLib.Converter.convert': incompatible type of parameter 1

**Comment by arteymix** [comment]
There's a breaking change on `convert` type annotation, they added a nullable (`?`) on the input buffer. I'll add a conditional preprocessor directive.

Just to be sure, it's vala 0.31?

**Comment by arteymix** [comment]
This might pose some problems, because they could be null-check on the buffer now. Would you mind testing the `fix-nullable-convert` branch?

**Comment by Matrix-Zhang** [comment]
ok, wait me two days....:)

**Comment by arteymix** [comment]
This is an issue with Vala and they [removed the annotation already](https://git.gnome.org/browse/vala/commit/vapi/gio-2.0.vapi?id=4313a9e42edbba774a6852bf095bf11bbef32e8d). @Matrix-Zhang just wait for the next release ;)

Moreover, `0.31.1` is a development release, so it's not worth fixing it.
