### ISSUE TITLE
Use Ubuntu 18.04 LTS as a bare minimum

### ISSUE THREAD

**Issue by arteymix** [valum-framework/valum#229]
Ubuntu 16.04.7 LTS reached end of standard support last April 2021.

New requirements:

 - glib, gobject, gio and gio-unix >= 2.56
 - libsoup2.4 >= 2.62
 - vala >= 0.40
 - meson >= 0.46
 - ninja-build >= 1.8.2

There's no point keeping supporting Ubuntu 14.04 and 16.04 LTS for the 0.4.

Reference: https://wiki.ubuntu.com/Releases

**Comment by arteymix** [comment]
@colinkiama that would be a good issue for you to work on!

**Comment by arteymix** [comment]
Besides removing code, there could be opportunities for using new features.

**Comment by arteymix** [comment]
Had to fix VSGI build for this to work: https://github.com/valum-framework/vsgi/commit/9aa80b01c7ceee79b2eee0a155525ffba072eb7e

**Comment by arteymix** [comment]
We now have a CI that builds on 18.04 LTS and 20.04 LTS.

**Comment by arteymix** [comment]
We could make a case of supporting 16.04 LTS if there aren't significant drawbacks of doing so.

**Comment by arteymix** [comment]
We need Meson 0.46 for pkgconfig.generate() to work properly. This one will need to come from pip.

**Comment by colinkiama** [comment]
> We could make a case of supporting 16.04 LTS if there aren't significant drawbacks of doing so.

Since GitHub removed the their Ubuntu 16.04 image, we'd have to find or make our own docker image. I'm not if this extra effort is worth it for an OS that is currently only receiving security maintenance updates at this point.

**Comment by arteymix** [comment]
Agreed. Only 18.04 and 20.04 have standard support for the forseeable future.

The next LTS will ship libsoup 3, and I'm considering using it for VSGI 1.0. This could be done in two steps: Valum & VSGI 0.4 with libsoup 2.4 and subsequently a Valum 1.0 with VSGI 1.0 and libsoup 3 when the 22.04 LTS is out.
