### ISSUE TITLE
Example does not compile for me

### ISSUE THREAD

**Issue by niansa** [valum-framework/valum#235]
Hey, when compiling the first example on the readme I get this error:

    ./main.vala:4.1-2.11: warning: main blocks are experimental
    ./valum/src/valum-router.vala:471.4-471.22: warning: `GLib.IOSchedulerJob.push' is deprecated
    ./valum/src/valum-router.vala:479.12-479.31: warning: `GLib.IOSchedulerJob.send_to_mainloop' is deprecated
    ./valum/src/valum-static.vala:101.25-101.55: warning: `GLib.FileInfo.get_modification_time' has been deprecated since 2.62
    ./valum/src/valum-static.vala:101.9-101.21: warning: `GLib.TimeVal' has been deprecated since 2.62
    ./valum/src/valum-static.vala:111.39-111.94: warning: `Soup.Date.to_timeval' is deprecated
    ./main.vala:10.12-10.26: error: The name `extend_utf8' does not exist in the context of `VSGI.Response'
        return res.extend_utf8 ("Hello world!");
               ^^^^^^^^^^^^^^^
    Compilation failed: 1 error(s), 6 warning(s)
    make: *** [Makefile:2: build] Error 1

Any hints on what I may be doing wrong?

**Comment by arteymix** [comment]
It's `expand_utf8`.

https://valadoc.org/vsgi-0.3/VSGI.Response.expand_utf8.html

**Comment by arteymix** [comment]
Oh, just noticed that our example in `README.md` is at fault here!

**Comment by arteymix** [comment]
Fixed in https://github.com/valum-framework/valum/commit/9523f6c8502d71bfc9c1f05163b5a96f701056ba

**Comment by niansa** [comment]
Amazing! Thanks. :-)

**Comment by arteymix** [comment]
Only a year or so later...
