### ISSUE TITLE
Unable to use valum as dependency using meson with readthedocs recipe

### ISSUE THREAD

**Issue by lennyhans** [valum-framework/valum#242]
Hi! I was trying to build the sample project using meson with subprojects but I faced a problem, the [docs suggest](https://valum-framework.readthedocs.io/en/latest/installation/#id1) that you should put valum dependency in this way

```meson
valum = subproject('valum').get_variable('valum')

```

But after reading the [meson docs about subprojects](https://mesonbuild.com/Subprojects.html) they suggest to

> ## Naming convention for dependency variables
> Ideally the dependency variable name should be of <project_name>_dep form. This way one can just use it without even looking inside build definitions of that subproject.

After changing that everything works

```meson
valum = subproject('valum').get_variable('valum_dep')

```

I think the docs are obsolete, because later I check the code and yeah, there is a file with this `valum/docs/getting-started.rst` that suggest the action, and also the `valum/src/meson.build` has the same name.

Thanks for your work!

**Comment by arteymix** [comment]
I've adjusted the documentation accordingly. The 0.3 series still uses the previous naming scheme.

**Comment by lennyhans** [comment]
Thanks!
