### ISSUE TITLE
Fully asynchronous operations

### ISSUE THREAD

**Issue by arteymix** [valum-framework/valum#35]
This is the next step for Valum once we will have a nice API.

`InputStream` and `OutputStream` already have the primitives for asynchronous operations, so we got to make them work with the request model. The FastCGI support enable the use of Request and Response as streamed objects.

**Comment by arteymix** [comment]
For testing heavy load, [httperf](http://www.hpl.hp.com/research/linux/httperf/httperf-man-0.9.txt) is an incredible tool!

**Comment by antono** [comment]
Siege is also cool :)
http://www.joedog.org/siege-home/

**Comment by arteymix** [comment]
Asynchronous operations work!

It all work with GIO and a MainLoop, so we can do asynchronous operations without even using threads. Events are triggered using a [IOSource](http://www.valadoc.org/#!api=glib-2.0/GLib.IOSource)

Introducing `GLib.Application` was an excellent idea as we can not parametrize the runtime with a specific socket, port, etc... and it has an included `MainLoop`!

I will release those changes this summer when I will have them worked out. It has a lot of potential: we are nearly beating Node.js :+1:

**Comment by arteymix** [comment]
VSGI.Application handler is an asynchronous function, so requests are inherently processing asynchonously.
