### ISSUE TITLE
Examples should be executed from their folder

### ISSUE THREAD

**Issue by arteymix** [valum-framework/valum#38]
It is not a good thing to have relative path from the top of the project in examples.

In order to execute an app, we should do something like:

```bash
cd exaples/app/
./app
```

**Comment by arteymix** [comment]
Building the examples with [GLib.Resource](http://valadoc.org/#!api=gio-2.0/GLib.Resource) is a much better approach for distributing static content from application.

I updated the sample application to use linked resources.

**Comment by antono** [comment]
:+1:

**Comment by arteymix** [comment]
It works, but it will take a bit before getting in the trunk as it depends on a finished implementation of CTPL.
