### ISSUE TITLE
CTPL binding is incomplete

### ISSUE THREAD

**Issue by arteymix** [valum-framework/valum#43]
We really need a complete support of CTPL api.

I have sent a mail to the CTPL guy to see if he plans to distribute a vapi.

If not, I think I could integrate vapigen in CTPL development trunk https://wiki.gnome.org/Projects/Vala/UpstreamGuide#Autotools_Integration, but I think you have already started something about this @antono. 

Have the vapi been generated or hand-written?

**Comment by antono** [comment]
This vapi was copy pasted from smeon's repository. Unfortunately i cannot remember who it was. Maybe you can find in vala-list on lists gnome.org

**Comment by arteymix** [comment]
Yeah, I have contacted the people at CTPL and they plan to eventually produce a GIR file.

**Comment by arteymix** [comment]
CTPL 0.3.4 is out! I will try to generate GIR using `waf`.

**Comment by arteymix** [comment]
This is blocked by CTPL as far as I am concerned. Let's just wait and see, maybe I'll try to hack it later :)

**Comment by arteymix** [comment]
There's been some progress on GIR integration in [CTPL repository](https://github.com/b4n/ctpl) and we're looking forward a better binding for Vala ;)

@b4n here's the issue

**Comment by arteymix** [comment]
Does not matter since of #145

**Comment by b4n** [comment]
I'm terribly sorry I never yet finished the CTPL GI stuff :/  It wasn't the first thing in my todo and the path to success was riddled with obstacles, but that doesn't change the fact I said I'd do something and I still didn't.
