### ISSUE TITLE
Make Tpl compatible with all Gee collections

### ISSUE THREAD

**Issue by arteymix** [valum-framework/valum#5]
Gee has a `Collection` abstraction  we could take great benefits so that anything we pass to a template could be traversed and rendered.

**Comment by arteymix** [comment]
I have worked on it and figured out it would be cleaner to just expose the `Ctpl.Environ` and provide extra methods in `View` to push collections, maps, arrays of primitive types and `Value?`.

Everything is in the [ctpl-as-view](6caca5ece4f4bcce0fb902ed9886e223bb2fc8d4) branch.

**Comment by antono** [comment]
Personally i would like to have `mustache` written in Vala with `Gee` types integrated. But this needs much more work.

**Comment by arteymix** [comment]
Yes, me too, Ctpl is very limited in terms of features, but it integrates quite nicely and it has a elegant syntax.

Anyway, I think that Valum will first be used to design high-performance api, so I am not worried too much about the templating solution we have right now.

**Comment by arteymix** [comment]
Merged!
