### ISSUE TITLE
Segfault happens when using CTPL

### ISSUE THREAD

**Issue by kirushyk** [valum-framework/valum#61]
GET to /ctpl/foo/bar causes Valum demo app it to crash

** Message: tpl.vala:82: 2
Segmentation fault

**Comment by arteymix** [comment]
CTPL integration has been rewritten in the [ctpl-as-view](https://github.com/valum-framework/valum/tree/ctpl-as-view) branch.

The integration is much cleaner and work with `Ctpl.Environ` to hold variables rather than a simple `Map`.

It works and it is minimally tested if you want to play with it.

**Comment by arteymix** [comment]
I merged the said branch!
